### PR TITLE
preparing for PyPI publishing.

### PR DESCRIPTION
**Pull request by mrtizmoatwork**
only thing left to do is to add a check to ensure that the git tag == setup.py version string.

### CODE REVIEW

**Comment by mrtizmoatwork** [comment]
Important note @myhndl when tagging a release, we need to annotate the tag for this to work optimally.

The command used to tag the branch should be like this:

`git tag -a -s -m "release 0.2.4" 0.2.4`

That is an annotated tag that is signed with an annotation message.

-m: message
-a: annotated
-s: signed

**Comment by mrtizmoatwork** [comment]
Tagging via the GitHub UI should also create an annotated tag if you include a message.

**Comment by myhndl** [comment]
Wouldn't it be better to just `git describe --tags`

**Comment by mrtizmoatwork** [comment]
you can choose which ever you want:

Here is the most useful link I found:
https://stackoverflow.com/questions/1404796/how-to-get-the-latest-tag-name-in-current-branch-in-git

**Comment by mrtizmoatwork** [comment]
Important quote "Unless the tags are annotated tags, I think there is no way for git to distinguish which of the two was created earlier. " on that page.

**Comment by myhndl** [comment]
Ah gotcha, okay annotated it is!

**Pull request merged**
