### PR TITLE
Resolve memory leak by removing pending_bounties

### PR DESCRIPTION
**Pull request by Rizato**
Removes `pending_bounties` from abstractarbiter and abstractmicroengine.

`pending_bounites` was intended to deduplicate bounties due having multiple blockchains nodes.
Deduplication was important to avoid rescanning a file again, which would add roadblocks to scanning new bounties in time.
It was also important to stop wasting transactions with duplicate settle attempts.
    
Originally, an item was added to `pending_bounites`, and removed upon settle.
In our current system, where settles are temporarily disabled, `pending_bounties` grows forever.
    
We long ago solved the duplication issue, and settles will no longer be the microengine's responsibility.
`pending_bounites` is no longer necessary, and was honestly always doomed to fail when we increased the settle time to 7 days.

### CODE REVIEW

**Review by mrtizmoatwork — APPROVED** [review]
ok

**Review by alanjds — DISMISSED** [review]

**Comment by mrtizmoatwork** [comment]
hey @Rizato while you are at it, can you update the `.gitlab-ci.yaml` to use the new runners?

**Comment by Rizato** [comment]
@mrtizmoatwork What should I be changing for that?

**Comment by Rizato** [comment]
Found the wiki

**Review by mrtizmoatwork — APPROVED** [review]
ok

**Pull request merged**
